# Generated by Django 4.0.2 on 2022-05-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcontributor_blog_contributors_blog_word_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
