# Generated by Django 4.0.2 on 2022-05-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
