# Generated by Django 4.0.2 on 2022-05-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_follows'),
    ]

    operations = [
    ]
